from __future__ import print_function
__author__ = 'Leanne Whitmore'
__email__ = 'lwhitmo@sandia.gov'
__description__ = 'Tests GenBank module'

import os
import re
import unittest
from GenBank import genbank_functions as gf
PATH = os.path.dirname(os.path.abspath(__file__))
PPATH = re.sub('tests', '', PATH)

class RunGenbankFunctions(unittest.TestCase):
    def setUp(self):
        """Initialize before every test."""
        print ("Initializing tests")


    def tearDown(self):
        """Clean up after each test."""
    
    def test_extract_GenBank_sequence(self):
        """test function extract_GenBank_data"""
        geneseqorig = "agcaatattacaactaacaataaaaatgtcttccattagcataaacatagctatgccactgaattccctccacaactttgagaggaaaccttcaaaagcatggtctacctcttgcactgcacccgcagctcgcctccgggcatcttcctccttacaacaagaaaaacctcaccaaatccgacgctctggggattaccaaccctctctttgggatttcaattacatacagtctctcaacactccgtataaggagcagagacactttaataggcaagcagagttgattatgcaagtgaggatgttgctcaaggtaaagatggaggcaattcaacagttggagttgattgatgacttgcaatacctgggactgtcttatttctttcaagatgagattaaacaaatcttaagttctatacacaatgagcccagatatttccacaataatgatttgtatttcacagctcttggattcagaatcctcagacaacatggttttaatgtttccgaagatgtatttgattgtttcaaaattgagaagtgcagtgatttcaatgcaaaccttgctcaagatacgaagggaatgttacaactttatgaagcatctttccttttgagagaaggtgaagatacattggagctagcaagacgattttccaccagatctctacgagaaaaatttgatgaaggtggtgatgaaattgatgaagatctatcatcgtggattcgccattccttggatcttcctcttcattggagggtccaaggattagaggcaagatggttcttagatgcttatgcgaggaggccggacatgaatccacttattttcaaactcgccaaactcaacttcaatattgttcaggcaacatatcaagaagaactgaaagatatctcaaggtggtggaatagttcgtgccttgctgagaaactcccatttgtgagagataggattgtggaatgcttcttttgggccatcgcggcttttgagcctcaccaatatagttatcagagaaaaatggccgccgttattattactttcataacaattatcgatgatgtttatgatgtgtatggaacaatagaagaactagaactattaacagatatgattcgcagatgggataataaatcaataagccaacttccatattatatgcaagtgtgctatttggcactatacaacttcgtttctgagcgggcttacgatattctaaaagatcaacatttcaacagcatcccatatttacagagatcgtgggtaagtttggttgaaggatatcttaaggaggcatactggtactacaatggctataaaccaagcttggaagaatatctcaacaacgccaagatttcaatatcggctcctacaatcatatcccagctttattttacattagcaaactcgattgatgaaacagctatcgagagcttgtaccaatatcataacatactttacctatcaggaaccatattaaggcttgctgacgatcttgggacatcacaacatgagctggagagaggagacgtaccgaaagcaatccagtgctacatgaatgacacaaatgcttcggagagagaggcggtggaacacgtgaagtttctgataagggaggcgtggaaggagatgaacacggtcacaacagccagcgattgtccgtttacggatgatttggttgcggccgcagctaatcttgcaagggcggctcagtttatatatctcgacggggatgggcatggcgtgcaacactcagaaatacatcaacagatgggaggcctgctattccagccttatgtctgaataaatcgaaaatccaacctactatgtatccctcgataatatattcttggggttaacatgtttaattaaagttctaattdaaagagctgaatcgatcctcaaaaaaaaaaaaaa"
        protseqorig = "MSSISINIAMPLNSLHNFERKPSKAWSTSCTAPAARLRASSSLQQEKPHQIRRSGDYQPSLWDFNYIQSLNTPYKEQRHFNRQAELIMQVRMLLKVKMEAIQQLELIDDLQYLGLSYFFQDEIKQILSSIHNEPRYFHNNDLYFTALGFRILRQHGFNVSEDVFDCFKIEKCSDFNANLAQDTKGMLQLYEASFLLREGEDTLELARRFSTRSLREKFDEGGDEIDEDLSSWIRHSLDLPLHWRVQGLEARWFLDAYARRPDMNPLIFKLAKLNFNIVQATYQEELKDISRWWNSSCLAEKLPFVRDRIVECFFWAIAAFEPHQYSYQRKMAAVIITFITIIDDVYDVYGTIEELELLTDMIRRWDNKSISQLPYYMQVCYLALYNFVSERAYDILKDQHFNSIPYLQRSWVSLVEGYLKEAYWYYNGYKPSLEEYLNNAKISISAPTIISQLYFTLANSIDETAIESLYQYHNILYLSGTILRLADDLGTSQHELERGDVPKAIQCYMNDTNASEREAVEHVKFLIREAWKEMNTVTTASDCPFTDDLVAAAANLARAAQFIYLDGDGHGVQHSEIHQQMGGLLFQPYV"
        geneseq, protseq = gf.extract_GenBank_sequence('AF051901')
        protseq = re.sub('"', '', protseq)
        geneseq = re.sub('"', '', geneseq)
        self.assertEqual(geneseq, geneseqorig)
        self.assertEqual(protseq, protseqorig)

        geneseqorig = "atggacatgcctgcaaaagaagaaaaagtaattcgtcccattgtccactttcctcctagcgtttgggcagaccagtttctcatcttcgacgacaagcaggcagagcaagccaatatagaacaagtagttaatgagttaagagaagatgtgagaaaagatttagtgtcatctttagatgttcaagcgaagcacacaaatttgttaaaacttattgatgctatccaacgtcttggtatagcgtatcattttgaagaggagattgagcaagccttacaacatatttatgatacctatggtgatgactggaaaggcagaagcccttccctttggttccgaatccttcggcaacaaggtttttatgtttcttgtgatatttttaaaaactataaaaaagtggatggttcatttaaggaatccctcaccaacgatgtagaaggcttgcttgagctgtacgaggcaacatatttgagagtgcaaggcgaaggggttctagatgatgctcttgttttcacaaggacttgtcttgagaaaatagcaaaggatcttgttcacagcaaccctacactatctacacacatacaagaagagctaaaacagccgttacataaaaggttgacaagactagaggcattgcgttacattcctatgtacgaacaacaagcatctcataatgagtctttactcaaacttgcgaagctaggtttcaacttacttcaatcattgcatagaaaggagcttagcgaagtttccaggtggtggaaaggtcttgatgtcccaaacaatctaccttatgcaagagatagaatggttgaatgttatttttgggcactaggtgtctattttgagccaaaatattctcgagctaggatctttttagcaaaagtaatttcgctagcaactgttcttgacgacacttatgatgcttatggaacctatgaagaacttaagatctttactgaagcaattcaaaggtggtcgattacatgcatagatatgcttccagaatacatgaaactattataccaaggagtcttggatatatacaaagaaatggaagaaataatgggaaaagagggaaaagcacatcatcttagctatgctaaagaatctatgaaagagtttattagaagctatatgatggaagcaaaatgggcaaatgaggggtatgtaccaacagcagaggagcatatgtcagttgcgtttgtaagcagcgggtatagcatgcttgcaacaacatgttttgttggcatgggtgatatcgttacagatgaagcattcaaatgggctctgacaaaacctcctatcatcaaagcttcatgtgcaattgctagactcatggatgatattcactctcaaaaggaggagaaagaaagaatacatgttgcatctagtgttgaaagttacatgaagcaatatgatgtgacagaggagcatgtccttaaagtatttaacaagaaaatcgaggatgcgtggaaagatataacccgagaatcccttgtgcgtaaagatattccgatgcctctgatgatgcgagtgattaacttggcacaggtgatggatgttttatataaacataaagacggtttcactaatgtgggagaagaactcaaggatcatattaaatctttgctcgttcatcctatacctatataa"
        protseqorig = "MDMPAKEEKVIRPIVHFPPSVWADQFLIFDDKQAEQANIEQVVNELREDVRKDLVSSLDVQAKHTNLLKLIDAIQRLGIAYHFEEEIEQALQHIYDTYGDDWKGRSPSLWFRILRQQGFYVSCDIFKNYKKVDGSFKESLTNDVEGLLELYEATYLRVQGEGVLDDALVFTRTCLEKIAKDLVHSNPTLSTHIQEELKQPLHKRLTRLEALRYIPMYEQQASHNESLLKLAKLGFNLLQSLHRKELSEVSRWWKGLDVPNNLPYARDRMVECYFWALGVYFEPKYSRARIFLAKVISLATVLDDTYDAYGTYEELKIFTEAIQRWSITCIDMLPEYMKLLYQGVLDIYKEMEEIMGKEGKAHHLSYAKESMKEFIRSYMMEAKWANEGYVPTAEEHMSVAFVSSGYSMLATTCFVGMGDIVTDEAFKWALTKPPIIKASCAIARLMDDIHSQKEEKERIHVASSVESYMKQYDVTEEHVLKVFNKKIEDAWKDITRESLVRKDIPMPLMMRVINLAQVMDVLYKHKDGFTNVGEELKDHIKSLLVHPIPI"
        geneseq, protseq = gf.extract_GenBank_sequence('KC118534')
        protseq = re.sub('"', '', protseq)
        geneseq = re.sub('"', '', geneseq)
        self.assertEqual(geneseq, geneseqorig)
        self.assertEqual(protseq, protseqorig)
if __name__ == '__main__':
    unittest.main(exit=False)