from __future__ import print_function
__author__ = 'Leanne Whitmore'
__email__ = 'lwhitmo@sandia.gov'
__description__ = 'Tests BLAST module'

import os
import re
import unittest
from BLAST import run_blast as rb

PATH = os.path.dirname(os.path.abspath(__file__))
PPATH = re.sub('tests', '', PATH)

class RunBLASTtests(unittest.TestCase):
    def setUp(self):
        """Initialize before every test."""
        print ("Initializing tests")

        self.IB = rb.ImplementBLAST('testblastdb', 'GCA_000023365.1',
                                    PATH+'/data/test_16S.fa', run=False)

    def tearDown(self):
        """Clean up after each test."""
        
        del self.IB

    def test_read_16S_fasta_file(self):
        """test function read_16S_fasta_file"""

        sequence = "AAATTGAAGAGTTTGATCATGGCTCAGATTGAACGCTGGCGGCAGGCCTAACACATGCAAGTCGAACGGTAACAGGAAGCAGCTTGCTGCTTCGCTGACGAGTGGCGGACGGGTGAGTAATGTCTGGGAAACTGCCTGATGGAGGGGGATAACTACTGGAAACGGTAGCTAATACCGCATAACGTCGCAAGACCAAAGAGGGGGACCTTCGGGCCTCTTGCCATCGGATGTGCCCAGATGGGATTAGCTTGTTGGTGGGGTAACGGCTCACCAAGGCGACGATCCCTAGCTGGTCTGAGAGGATGACCAGCCACACTGGAACTGAGACACGGTCCAGACTCCTACGGGAGGCAGCAGTGGGGAATATTGCACAATGGGCGCAAGCCTGATGCAGCCATGCCGCGTGTATGAAGAAGGCCTTCGGGTTGTAAAGTACTTTCAGCGGGGAGGAAGGGAGTAAAGTTAATACCTTTGCTCATTGACGTTACCCGCAGAAGAAGCACCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCACGCAGGCGGTTTGTTAAGTCAGATGTGAAATCCCCGGGCTCAACCTGGGAACTGCATCTGATACTGGCAAGCTTGAGTCTCGTAGAGGGGGGTAGAATTCCAGGTGTAGCGGTGAAATGCGTAGAGATCTGGAGGAATACCGGTGGCGAAGGCGGCCCCCTGGACGAAGACTGACGCTCAGGTGCGAAAGCGTGGGGAGCAAACAGGATTAGATACCCTGGTAGTCCACGCCGTAAACGATGTCGACTTGGAGGTTGTGCCCTTGAGGCGTGGCTTCCGGAGCTAACGCGTTAAGTCGACCGCCTGGGGAGTACGGCCGCAAGGTTAAAACTCAAATGAATTGACGGGGGCCCGCACAAGCGGTGGAGCATGTGGTTTAATTCGATGCAACGCGAAGAACCTTACCTGGTCTTGACATCCACGGAAGTTTTCAGAGATGAGAATGTGCCTTCGGGAACCGTGAGACAGGTGCTGCATGGCTGTCGTCAGCTCGTGTTGTGAAATGTTGGGTTAAGTCCCGCAACGAGCGCAACCCTTATCCTTTGTTGCCAGCGGTCCGGCCGGGAACTCAAAGGAGACTGCCAGTGATAAACTGGAGGAAGGTGGGGATGACGTCAAGTCATCATGGCCCTTACGACCAGGGCTACACACGTGCTACAATGGCGCATACAAAGAGAAGCGACCTCGCGAGAGCAAGCGGACCTCATAAAGTGCGTCGTAGTCCGGATTGGAGTCTGCAACTCGACTCCATGAAGTCGGAATCGCTAGTAATCGTGGATCAGAATGCCACGGTGAATACGTTCCCGGGCCTTGTACACACCGCCCGTCACACCATGGGAGTGGGTTGCAAAAGAAGTAGGTAGCTTAACCTTCGGGAGGGCGCTTACCACTTTGTGATTCATGACTGGGGTGAAGTCGTAACAAGGTAACCGTAGGGGAACCTGCGGTTGGATCACCTCCTTA"
        self.IB.read_16S_fasta_file()
        self.assertEqual(len(self.IB.fasta16S), 10)
        self.assertEqual(''.join(self.IB.fasta16S['GCA_000091005.1']), sequence)

    def test_generate_temp_query_file(self):
        """test function generate_temp_query_file"""

        sequence = 'AGAGTTTGATCATGGCTCAGATTGAACGCTGGCGGCAGGCCTAACACATGCAAGTCGAACGGTAACAGGAAACAGCTTGCTGTTTCGCTGACGAGTGGCGGACGGGTGAGTAATGTCTGGGAAACTGCCTGATGGAGGGGGATAACTACTGGAAACGGTAGCTAATACCGCATAACGTCGCAAGACCAAAGAGGGGGACCCTCGGGCCTCTTGCCATCGGATGTGCCCAGATGGGATTAGCTTGTTGGTGGGGTAACGGCTCACCAAGGCGACGATCCCTAGCTGGTCTGAGAGGATGACCAGCCACACTGGAACTGAGACACGGTCCAGACTCCTACGGGAGGCAGCAGTGGGGAATATTGCACAATGGGCGCAAGCCTGATGCAGCCATGCCGCGTGTATGAAGAAGGCCTTCGGGTTGTAAAGTACTTTCAGCGGGGAGGAAGGGAGTAAAGTTAATACCTTTGCTCATTGACGTTACCCGCAGAAGAAGCACCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCACGCAGGCGGTTTGTTAAGTCAGATGTGAAATCCCCGGGCTCAACCTGGGAACTGCATCTGATACTGGCAAGCTTGAGTCTCGTAGAGGGGGGTAGAATTCCAGGTGTAGCGGTGAAATGCGTAGAGATCTGGAGGAATACCGGTGGCGAAGGCGGCCCCCTGGACGAAGACTGACGCTCAGGTGCGAAAGCGTGGGGAGCAAACAGGATTAGATACCCTGGTAGTCCACGCCGTAAACGATGTCGACTTGGAGGTTGTGCCCTTGAGGCGTGGCTTCCGGAGCTAACGCGTTAAGTCGACCGCCTGGGGAGTACGGCCGCAAGGTTAAAACTCAAATGAATTGACGGGGGCCCGCACAAGCGGTGGAGCATGTGGTTTAATTCGATGCAACGCGAAGAACCTTACCTGGTCTTGACATCCACGGAAGTTTTCAGAGATGAGAATGTGCCTTCGGGAACCGTGAGACAGGTGCTGCATGGCTGTCGTCAGCTCGTGTTGTGAAATGTTGGGTTAAGTCCCGCAACGAGCGCAACCCTTATCCTTTGTTGCCAGCGGTCCGGCCGGGAACTCAAAGGAGACTGCCAGTGATAAACTGGAGGAAGGTGGGGATGACGTCAAGTCATCATGGCCCTTACGACCAGGGCTACACACGTGCTACAATGGCGCATACAAAGAGAAGCGACCTCGCGAGAGCAAGCGGACCTCATAAAGTGCGTCGTAGTCCGGATTGGAGTCTGCAACTCGACTCCATGAAGTCGGAATCGCTAGTAATCGTGGATCAGAATGCCACGGTGAATACGTTCCCGGGCCTTGTACACACCGCCCGTCACACCATGGGAGTGGGTTGCAAAAGAAGTAGGTAGCTTAACCTTCGGGAGGGCGCTTACCACTTTGTGATTCATGACTGGGGTGAAGTCGTAACAAGGTAACCGTAGGGGAACCTGCGGTTGGATCACCT'
        self.IB.read_16S_fasta_file()
        self.IB.generate_temp_query_file()
        self.assertEqual(''.join(self.IB.fasta16S['GCA_000023365.1']), sequence)
        self.assertTrue(os.path.isfile(PPATH+'query/temp_input_query.fa'))

    def test_generate_blast_dbs(self):
        """test function generate_blast_dbs"""

        self.IB.generate_blast_dbs()
        self.assertTrue(os.path.isfile(PPATH+'blastdbs/testblastdb.nhr'))
        self.assertTrue(os.path.isfile(PPATH+'blastdbs/testblastdb.nin'))
        self.assertTrue(os.path.isfile(PPATH+'blastdbs/testblastdb.nsq'))

    def test_blastn_sequences(self):
        """test function blastn_sequences"""

        self.IB.read_16S_fasta_file()
        self.IB.generate_temp_query_file()
        self.IB.generate_blast_dbs()
        self.IB.blastn_sequences()

        self.assertTrue(os.path.isfile(PPATH+'blastoutput/blast_out_GCA_000023365.1.txt'))
    
    def test_process_blast_output(self):
        """test function process_blast_output"""

        self.IB.blastn_sequences()
        self.IB.generate_blast_dbs()
        self.IB.process_blast_output()
 
        ###TEST NUMBER OF ENTRIES IN DICT###
        self.assertEqual(len(self.IB.blast_results), 10)
        self.assertEqual(len(self.IB.blast_bitscore), 10)
        ###TEST ENTRIES IN blast_bitscore###
        self.assertEqual(self.IB.blast_bitscore['GCA_000262125.1'], '2732')
        self.assertEqual(self.IB.blast_bitscore['GCF_000008865.2'], '2732')
        self.assertEqual(self.IB.blast_bitscore['GCA_000021125.1'], '2726')
        ###TEST ENTRIES IN blast_results###
        self.assertEqual(self.IB.blast_results[10], 'GCA_000021125.1')
        self.assertEqual(self.IB.blast_results[3], 'GCA_000262125.1')
        self.assertEqual(self.IB.blast_results[1], 'GCA_000023365.1')

if __name__ == '__main__':
    unittest.main(exit=False)
    os.remove(PPATH+'blastdbs/testblastdb.nsq')
    os.remove(PPATH+'blastdbs/testblastdb.nhr')
    os.remove(PPATH+'blastdbs/testblastdb.nin')
    os.remove(PPATH+'query/temp_input_query.fa')
