from __future__ import print_function
__author__ = 'Leanne Whitmore'
__email__ = 'lwhitmo@sandia.gov'
__description__ = 'Tests geneSeqs_KEGG module'

import os
import re
import pickle
import unittest
from retrievegeneseqs import geneSeqs_KEGG as gse

class RunGeneSeqsKEGG(unittest.TestCase):
    def setUp(self):
        """Initialize before every test."""
        print ("Initializing tests")

    def tearDown(self):
        """Clean up after each test."""

    def tests_get_geneseq_for_1(self):
        GSK = gse.GeneSeqKEGG(orgs2pullgene=False, get_orgs=True)
        GSK.get_geneseq_for('4.2.3.110')
        self.assertEqual(len(GSK.orgs_with_enzyme), 0)

    def tests_get_geneseq_for_2(self):
        cds_4_3_3_110 = 'atgtcttccattagcataaacatagctatgccactgaattccctccacaactttgagaggaaaccttcaaaagcatggtctacctcttgcactgcacccgcagctcgcctccgggcatcttcctccttacaacaagaaaaacctcaccaaatccgacgctctggggattaccaaccctctctttgggatttcaattacatacagtctctcaacactccgtataaggagcagagacactttaataggcaagcagagttgattatgcaagtgaggatgttgctcaaggtaaagatggaggcaattcaacagttggagttgattgatgacttgcaatacctgggactgtcttatttctttcaagatgagattaaacaaatcttaagttctatacacaatgagcccagatatttccacaataatgatttgtatttcacagctcttggattcagaatcctcagacaacatggttttaatgtttccgaagatgtatttgattgtttcaaaattgagaagtgcagtgatttcaatgcaaaccttgctcaagatacgaagggaatgttacaactttatgaagcatctttccttttgagagaaggtgaagatacattggagctagcaagacgattttccaccagatctctacgagaaaaatttgatgaaggtggtgatgaaattgatgaagatctatcatcgtggattcgccattccttggatcttcctcttcattggagggtccaaggattagaggcaagatggttcttagatgcttatgcgaggaggccggacatgaatccacttattttcaaactcgccaaactcaacttcaatattgttcaggcaacatatcaagaagaactgaaagatatctcaaggtggtggaatagttcgtgccttgctgagaaactcccatttgtgagagataggattgtggaatgcttcttttgggccatcgcggcttttgagcctcaccaatatagttatcagagaaaaatggccgccgttattattactttcataacaattatcgatgatgtttatgatgtgtatggaacaatagaagaactagaactattaacagatatgattcgcagatgggataataaatcaataagccaacttccatattatatgcaagtgtgctatttggcactatacaacttcgtttctgagcgggcttacgatattctaaaagatcaacatttcaacagcatcccatatttacagagatcgtgggtaagtttggttgaaggatatcttaaggaggcatactggtactacaatggctataaaccaagcttggaagaatatctcaacaacgccaagatttcaatatcggctcctacaatcatatcccagctttattttacattagcaaactcgattgatgaaacagctatcgagagcttgtaccaatatcataacatactttacctatcaggaaccatattaaggcttgctgacgatcttgggacatcacaacatgagctggagagaggagacgtaccgaaagcaatccagtgctacatgaatgacacaaatgcttcggagagagaggcggtggaacacgtgaagtttctgataagggaggcgtggaaggagatgaacacggtcacaacagccagcgattgtccgtttacggatgatttggttgcggccgcagctaatcttgcaagggcggctcagtttatatatctcgacggggatgggcatggcgtgcaacactcagaaatacatcaacagatgggaggcctgctattccagccttatgtctga'
        GSK = gse.GeneSeqKEGG(orgs2pullgene=True, get_orgs=False)
        GSK.get_geneseq_for('4.2.3.110')
        self.assertEqual(GSK.genesequences['4.2.3.110']['ag']['aac26018'], cds_4_3_3_110)

    def tests_get_geneseq_for_3(self):
        orgs = ['eco']
        cds_1_1_1_1_b0356 = "atgaaatcacgtgctgccgttgcatttgctcccggtaaaccgctggaaatcgttgaaattgacgttgcaccaccgaaaaaaggtgaagtgctaattaaagtcacccataccggcgtttgccataccgacgcatttaccctctccggcgatgacccggaaggtgtattcccggtggttctcggtcacgaaggggccggcgttgtggttgaagtcggtgaaggcgtaaccagcgtcaaacctggcgaccatgtgatcccgctttacaccgcggagtgcggcgagtgtgagttctgtcgttctggcaaaactaacctctgtgttgcggttcgcgaaacccagggtaaaggcctgatgccagacggcaccacccgtttttcttacaacgggcagccgctttatcactacatggggtgctctacattcagtgaatacaccgtagtcgcggaagtgtctctggcaaaaattaatccagaagcaaaccatgaacacgtctgcctgctgggctgtggcgtgaccaccggtattggcgcggtacacaacacagctaaagtccagccaggtgattctgttgccgtgtttggtcttggcgcgattggtctggcagtggttcagggcgcgcgtcaggcgaaagcgggtcggattatcgctatcgataccaacccgaagaaattcgatctggcgcgtcgcttcggtgctaccgactgcattaacccgaatgactacgacaaaccgataaaagatgtcctgttggatatcaacaaatggggtatcgaccatacctttgaatgcatcggtaacgtcaacgtgatgcgtgcggcgctggaaagtgcgcaccgcggctggggtcagtcggtgatcatcggggtcgcggttgccggtcaggaaatctccacccgtccattccagttggtcactggtcgcgtatggaaaggttccgcgtttggcggcgtgaaaggtcgttcccagttaccgggcatggttgaagatgcgatgaaaggtgatatcgatctggaaccgtttgtcacgcataccatgagcctggatgaaattaatgacgccttcgacctgatgcatgaaggcaaatccattcgaaccgtaattcgttactga"
        GSK = gse.GeneSeqKEGG(orgs2pullgene=orgs, get_orgs=False)
        GSK.get_geneseq_for('1.1.1.1')
        self.assertEqual(len(GSK.genesequences['1.1.1.1']['eco']), 4)
        self.assertEqual(GSK.genesequences['1.1.1.1']['eco']['b0356'], cds_1_1_1_1_b0356)

    def tests_get_geneseq_for_4(self):
        orgs = ['cpv']
        cds_1_1_1_1_cgd8_1720 = "ttaaaggtggaagtagctcagaaagcttttttaaaactttctcaagagcaagttgattatatttttcaaagagcttccttggcagcaaactgtgcaagatatgagttggcagtattagcaatagaagatggtggaatgggattgttagaggataagataataaagaatcactttgcatcagagaatatttataataagtacagaaatacaaagactgtaggagtaattgaacatgatgaatttggaggaattgatattgttgctgaaccattgggaattttggcaggaatctctccatgtacaaatccaacatctacaacgatcttcaaatccctcatctcccttaagacaagaaactgcatagtattttctcctcatccaagaactgctagaagctccataagagcagccaaaattatcagggatgcagcaatagaagcaggagctccagaggattgtattggttggatcgatgttgcaagtatttccttatgtaattccttaatgaaccatagctctgtcagtgccattctagcaacaggttcagtggctttggtgaaggcagcttattcatgtggaaaaccagccttgggaggaggagcaggaaattcaccagtattagttgatgaactctcagatttggaaatggttgtgaactcagtaattttatccaaaacatttgataacagtttaatttgcgcatccgaacaatgtttggtggttctagattcagtatatgataagttgatttctggattcaaaaatagaggagtacatatcatttcttcaaaagatgagctccagagacttgggaatttattaattgacgaaaatggaaatatgaatcctaaatctgttggaattagtgcagttgaaatcgcaaagatggcatccattgatatcccaaaagatgctgttatgattcttgctgaaatcaacgaaattggaagaggggagaaactgtctcacgaaaagttgtgtcctgtattgtcaatcatcagagctagcgactttaatgatggtgtttccaaggcaaaagccttagttgaatttggtggtttgggacacacatcttgtatatatactgacccaaattctgatgaaggaaaacgcagaattactgagttccagagaagcattcccactggaagagttctagtttgcatgccagctgctcaaggagcaatgggtgaaatgtttaacttccgtcaaactccttctttgactttgggatgtggttcctggggccatacttcaacagctgagggaattggtgtaaaacatttgcttaattacaagcaagttgtacaaagaagggaccacatctcctggtttaaggttccaccttctatttatttcaatagaggatgccttgaagaagctttacaagatctcaaagaaatcaatttaaagaaagcctacattattactgatagagtcatggttagtcttgggtttgttgataatcttattgaaggtctcaagtctgtaggagtagcctctgagatgtttgcagaagtccctcctgaacctgatgttgaaactgtcaaggaaattgttaaaagattaaatgtaagcaaaccagattgtcttattggttttggaggaggctctcctatggacgcttccaagcttgtaaggcttatgtatgaacatccaactgtcaaatggaatgaagttgttactagatttatggatattagaaagagaattgtcaaactacctcccagcggtggaaaaattcaaagatttatttgtattcctactacttctggtactggagcagaaatgactccatttgctgtaattactgataacagcactggaatcaaatatcctattgcttcttacaagcttactcctgatatggccattgttgatgccaactttgttctttctatgccaaggttccttgcagctgcaactggcttagatgctctaacacatgcccttgaagcttttgttgcaacctatgcttctgaatacactgatggactttgcattcaagctatgagacttatattcgatcatttgccaaactctgttatcaatgcagatgccaaggcaagagaatatgtacacaatgcttcatctattgctggtatggcattctcaaatgcttttcttggaatttgccatgctctagctcaccaactgggagctcaaatgcatattccacatggaattgcaaatgcaatacttttaccacatattatttcttacaatgcatctaatagaccaacaaaacagtccattctatctcagtacaagtatcctgtagcaaagagtagatatgcaaagcttgttgatatcttgcatttcaagtccaatcagagctttgatagtaatttggatcaagagagtattaatattagaattctagttgaagcaatacaaaatctcaagaaaacattacaagttccaatgtgtgttaaagatcatggaatagaggaagaacattatatgtcaaaagttgagtctatgagtatccatgctcttgatgatcaatgtgtgggagctaatccaagattccctcttttaaatgagattaaacaactctatattgacgcttattctggatttgtcagatatccagaacattaa"
        GSK = gse.GeneSeqKEGG(orgs2pullgene=orgs, get_orgs=False)
        GSK.get_geneseq_for('1.1.1.1')
        self.assertEqual(len(GSK.genesequences['1.1.1.1']['cpv']), 1)
        self.assertEqual(GSK.genesequences['1.1.1.1']['cpv']['cgd8_1720'], cds_1_1_1_1_cgd8_1720)

if __name__ == '__main__':
    unittest.main(exit=False)